name: moodapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Update SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  intl: ^0.20.2
  keyboard_actions: ^4.2.0
  fluttertoast: ^8.2.10
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/LoGo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Update lints

flutter:
  uses-material-design: true
  assets:
   - assets/LoGo.png
